package io.chariot.async.api.generator.utils;

import io.chariot.async.api.generator.AsyncApiGenerator;
import io.chariot.async.api.generator.languages.TargetLanguage;

/**
 * Методы для работы с генерированным кодом.
 * */
public class GeneratorHelper {

    public static final String importGeneratedAnnotation = "javax.annotation.processing.Generated;";

    public static final String generatedAnnotationJava =
            String.format("@Generated(value=\"Generated by io.chariot:async-api-generator:%s\", date= \"%s\")",
                AsyncApiGenerator.appVersion,
                AsyncApiGenerator.generationTs);
    public static final String generatedAnnotationKotlin =
            String.format("@Generated(value=[\"Generated by io.chariot:async-api-generator:%s\"], date= \"%s\")",
                    AsyncApiGenerator.appVersion,
                    AsyncApiGenerator.generationTs);

    public static final String generatedFileHeaderComment = """
/**
* This file was generated by io.chariot:async-api-generator.
* DO NOT CHANGE THIS FILE!
* Update the source async API specification and regenerate the code instead.
*/
""";

    public static String getGeneratedAnnotation(TargetLanguage language) {
        switch (language) {
            case JAVA:
                return generatedAnnotationJava;

            case KOTLIN:
                return generatedAnnotationKotlin;
            default:
                return "";
        }
    }

    public static String dehyphenizeClassName(String className) {
        var index = className.lastIndexOf("-");
        if (index == -1)  {
            return className;
        }
        if (index >= className.length() - 1) {
            // TODO: сделать под флагом бросание исключения?
            var msg = "ERROR: className ends with hyphen: " + className;
            throw new IllegalArgumentException(msg);
        }

        while (index > -1) {
            var ch = className.substring(index + 1, index + 2);
            className = className.substring(0, index) + ch.toUpperCase() + className.substring(index + 2);

            index = className.lastIndexOf("-");
        }
        return className;
    }
}
